#!/bin/bash

function check_gcc()
{
	gcc --version
	if [ $? -ne 0 ]; then
		echo "You need to install gcc"
		exit 1
	fi	
}
function check_jnxlibc()
{
	echo "int main(){}" | cc -o /dev/null -x c - -ljnxc -ldl 2>/dev/null
	if [ $? -ne 0 ]; then
		git clone git://github.com/AlexsJones/jnxlibc.git

		if [ $? -ne 0 ]; then
			echo "Unable to clone, probably offline..."
			exit 1
		fi
		pushd jnxlibc
		./configure
		make
		sudo make install
		popd		
		rm -rf jnxlibc
	fi
}
echo "Checking system requirements..."
check_gcc
check_jnxlibc

make
sudo make install
