# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jonesax/Projects/pickle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jonesax/Projects/pickle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonesax/Projects/pickle/CMakeFiles /Users/jonesax/Projects/pickle/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonesax/Projects/pickle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pickle

# Build rule for target.
pickle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pickle
.PHONY : pickle

# fast build rule for target.
pickle/fast:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/build
.PHONY : pickle/fast

lib/src/compile.o: lib/src/compile.c.o
.PHONY : lib/src/compile.o

# target to build an object file
lib/src/compile.c.o:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/compile.c.o
.PHONY : lib/src/compile.c.o

lib/src/compile.i: lib/src/compile.c.i
.PHONY : lib/src/compile.i

# target to preprocess a source file
lib/src/compile.c.i:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/compile.c.i
.PHONY : lib/src/compile.c.i

lib/src/compile.s: lib/src/compile.c.s
.PHONY : lib/src/compile.s

# target to generate assembly for a file
lib/src/compile.c.s:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/compile.c.s
.PHONY : lib/src/compile.c.s

lib/src/executor.o: lib/src/executor.c.o
.PHONY : lib/src/executor.o

# target to build an object file
lib/src/executor.c.o:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/executor.c.o
.PHONY : lib/src/executor.c.o

lib/src/executor.i: lib/src/executor.c.i
.PHONY : lib/src/executor.i

# target to preprocess a source file
lib/src/executor.c.i:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/executor.c.i
.PHONY : lib/src/executor.c.i

lib/src/executor.s: lib/src/executor.c.s
.PHONY : lib/src/executor.s

# target to generate assembly for a file
lib/src/executor.c.s:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/executor.c.s
.PHONY : lib/src/executor.c.s

lib/src/filesys.o: lib/src/filesys.c.o
.PHONY : lib/src/filesys.o

# target to build an object file
lib/src/filesys.c.o:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/filesys.c.o
.PHONY : lib/src/filesys.c.o

lib/src/filesys.i: lib/src/filesys.c.i
.PHONY : lib/src/filesys.i

# target to preprocess a source file
lib/src/filesys.c.i:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/filesys.c.i
.PHONY : lib/src/filesys.c.i

lib/src/filesys.s: lib/src/filesys.c.s
.PHONY : lib/src/filesys.s

# target to generate assembly for a file
lib/src/filesys.c.s:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/filesys.c.s
.PHONY : lib/src/filesys.c.s

lib/src/main.o: lib/src/main.c.o
.PHONY : lib/src/main.o

# target to build an object file
lib/src/main.c.o:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/main.c.o
.PHONY : lib/src/main.c.o

lib/src/main.i: lib/src/main.c.i
.PHONY : lib/src/main.i

# target to preprocess a source file
lib/src/main.c.i:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/main.c.i
.PHONY : lib/src/main.c.i

lib/src/main.s: lib/src/main.c.s
.PHONY : lib/src/main.s

# target to generate assembly for a file
lib/src/main.c.s:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/main.c.s
.PHONY : lib/src/main.c.s

lib/src/parser.o: lib/src/parser.c.o
.PHONY : lib/src/parser.o

# target to build an object file
lib/src/parser.c.o:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/parser.c.o
.PHONY : lib/src/parser.c.o

lib/src/parser.i: lib/src/parser.c.i
.PHONY : lib/src/parser.i

# target to preprocess a source file
lib/src/parser.c.i:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/parser.c.i
.PHONY : lib/src/parser.c.i

lib/src/parser.s: lib/src/parser.c.s
.PHONY : lib/src/parser.s

# target to generate assembly for a file
lib/src/parser.c.s:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/parser.c.s
.PHONY : lib/src/parser.c.s

lib/src/scribe.o: lib/src/scribe.c.o
.PHONY : lib/src/scribe.o

# target to build an object file
lib/src/scribe.c.o:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/scribe.c.o
.PHONY : lib/src/scribe.c.o

lib/src/scribe.i: lib/src/scribe.c.i
.PHONY : lib/src/scribe.i

# target to preprocess a source file
lib/src/scribe.c.i:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/scribe.c.i
.PHONY : lib/src/scribe.c.i

lib/src/scribe.s: lib/src/scribe.c.s
.PHONY : lib/src/scribe.s

# target to generate assembly for a file
lib/src/scribe.c.s:
	$(MAKE) -f CMakeFiles/pickle.dir/build.make CMakeFiles/pickle.dir/lib/src/scribe.c.s
.PHONY : lib/src/scribe.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... pickle"
	@echo "... rebuild_cache"
	@echo "... lib/src/compile.o"
	@echo "... lib/src/compile.i"
	@echo "... lib/src/compile.s"
	@echo "... lib/src/executor.o"
	@echo "... lib/src/executor.i"
	@echo "... lib/src/executor.s"
	@echo "... lib/src/filesys.o"
	@echo "... lib/src/filesys.i"
	@echo "... lib/src/filesys.s"
	@echo "... lib/src/main.o"
	@echo "... lib/src/main.i"
	@echo "... lib/src/main.s"
	@echo "... lib/src/parser.o"
	@echo "... lib/src/parser.i"
	@echo "... lib/src/parser.s"
	@echo "... lib/src/scribe.o"
	@echo "... lib/src/scribe.i"
	@echo "... lib/src/scribe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

