#!/bin/bash
contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"
    then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}
increment_version ()
{
  declare -a part=( ${1//\./ } )
  declare    new
  declare -i carry=1

  for (( CNTR=${#part[@]}-1; CNTR>=0; CNTR-=1 )); do
    len=${#part[CNTR]}
    new=$((part[CNTR]+carry))
    [ ${#new} -gt $len ] && carry=1 || carry=0
    [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
  done
  new="${part[*]}"
  echo -e "${new// /.}"
} 

path=$1


cat $path | while IFS='' read -r LINE
do
	if contains $LINE "VERSION"
	then
		OLDIFS=IFS
		IFS="="
		read -a array <<< "$(printf "%s" "$LINE")"
		IFS=$OLDIFS
		echo "found -> ${array[1]}"
	fi
done



version='1.3.3.9'

increment_version $version
